name = "SuperHyde"
license = "MIT"
licenselink = "https://github.com/ageekymonk/hugo-superhyde-theme/blob/master/LICENSE.md"
description = "An elegant open source and mobile first theme"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.21

[author]
    name = "ramz"
    homepage = "http://blog.ageekymonk.com"

# If Porting existing theme
[original]
    name = "spf13"
    homepage = "http://spf13.com"
    repo = "https://www.github.com/spf13/hyde"